travis:
  secure:
    BINSTAR_TOKEN: t04uZNLP8XtnzUYFH/jwh9HreOvnW+p6Rz00M2KZZk4n+5vFa+2u5h7M4cEoGri+t/BxcRDmCtSsF3l7IyqBUEt5ZwMr3FxjZJhfL/YynwZxhnvlh21glYRl3NJCmEFvGpPs79BWq/WdQ9FryMmxg75czdgcCCCDeih0Jn6sxEIuzxXa2imviBKp7JUz3m8j8EWkIx5P5OhPE3PbHwCi0gGJ1KAfxuDiO3i+1OaIKR/QGne0UutYHDqdrUbjL+bcZKc2BYjICzjYI1vrD8eZaVVDqtEFbTKxypK9fuuAmJzhLdKgTR3fznBpV4f/PExle9+M7QzcgdKzpdaiAyYN529q/narQst70j7CE35eatkFrQa6PLD3IM3T7Mm4M/3wP4ZLhYZFiixdAiTREeNnUCk7658YAafIOZj5o0jj2qoh/MLYNnKr7dU1B3TRB2B83jW+AH/TJB916m4KrUQiKNcbTiF8NB2cnJ0wnlp0jmfsQsYse8UgoyrKziTZKUVWgOQrnQs6RSZs/pIJcaCVL/wPrBQLZvAmpRG/bFaRBUnVoh9W1pTmk9ksvc4hYEOwzWSbsL05x2+QSaxmr3KDDGximAeGUjUxJ5e6kTZ8tK8I611Ed1Y0RPeZkKXcDSQOQ8CnHJJzfHEphA4/g6MEGsvvvNVDraUZDMpxA6r/J/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
